version: '3.7'

services:

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    volumes:
      - ./gateway:/app
      - /app/node_modules
    ports:
      - 5000:5000
    networks:
      - mern-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - 3000:3000
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge